#!/usr/bin/env bash

# Configure your settings
# Name for the cluster/configuration files
NAME=""
# Ubuntu image to use
IMAGE="jammy"
# How many additional server instances to create
SERVER_COUNT_MACHINE="0"
# How many agent instances to create
AGENT_COUNT_MACHINE="1"
# How many CPUs to allocate to each machine
SERVER_CPU_MACHINE="4"
AGENT_CPU_MACHINE="4"
# How much disk space to allocate to each machine
SERVER_DISK_MACHINE="10G"
AGENT_DISK_MACHINE="10G"
# How much memory to allocate to each machine
SERVER_MEMORY_MACHINE="4G"
AGENT_MEMORY_MACHINE="4G"
# Install channel to use (embedded etcd is fully supported starting with v1.19.5+k3s1)
CHANNEL=stable
# Preconfigured secret to join the cluster (or autogenerated if empty)
SERVER_TOKEN=""
AGENT_TOKEN=""
# Merge generated kubeconfig with the current existing one (current existing one will be backed up). Set to "1" to trigger merge
MERGE_KUBECONFIG=""

ADDITIONAL_K3S_SERVER_OPTS="--disable=servicelb --disable=traefik"


K3S_VERSION="v1.26.1+k3s1" 

## Nothing to change after this line
if [ -x "$(command -v multipass.exe)" > /dev/null 2>&1 ]; then
    # Windows
    MULTIPASSCMD="multipass.exe"
elif [ -x "$(command -v multipass)" > /dev/null 2>&1 ]; then
    # Linux/MacOS
    MULTIPASSCMD="multipass"
else
    echo "The multipass binary (multipass or multipass.exe) is not available or not in your \$PATH"
    exit 1
fi
if [ -n "$MERGE_KUBECONFIG" ]; then
    if [ -z "$KUBECONFIG" ]; then
        KUBECONFIG="${HOME}/.kube/config"
    fi
fi

if [ -z $SERVER_TOKEN ]; then
    SERVER_TOKEN=$(cat /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1 | tr '[:upper:]' '[:lower:]')
    echo "No server token given, generated server token: ${SERVER_TOKEN}"
fi

if [ -z $AGENT_TOKEN ]; then
    AGENT_TOKEN=$(cat /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w 20 | head -n 1 | tr '[:upper:]' '[:lower:]')
    echo "No agent token given, generated agent token: ${AGENT_TOKEN}"
fi

# Check if name is given or create random string
if [ -z $NAME ]; then
    NAME="local"
    echo "No name given, generated name: ${NAME}"
fi

# check if cluster with $NAME already exists
CLUSTER_NAME="k3s-${NAME}"
K3S_SERVER_NAME="${CLUSTER_NAME}-server"
K3S_AGENT_NAME="${CLUSTER_NAME}-agent"

SERVER_EXISTS=$(multipass list | awk '{ print  $1 }' | tail -n +2 | grep -x ${K3S_SERVER_NAME})

if [ -n "$SERVER_EXISTS" ]; then
    echo "server $K3S_SERVER_NAME already exists, please choose a different NAME"
    exit 1
fi


echo "Creating cluster ${NAME} with $(( $SERVER_COUNT_MACHINE + 1 )) server(s) and ${AGENT_COUNT_MACHINE} agent(s)"

# Prepare cloud-init
# Cloud init template
read -r -d '' SERVER_INIT_CLOUDINIT_TEMPLATE << EOM
#cloud-config

runcmd:
 - '\curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$K3S_VERSION K3S_TOKEN=$SERVER_TOKEN K3S_AGENT_TOKEN=$AGENT_TOKEN INSTALL_K3S_EXEC="server --cluster-init" K3S_KUBECONFIG_MODE=644 sh -s - $ADDITIONAL_K3S_SERVER_OPTS'
EOM

echo "$SERVER_INIT_CLOUDINIT_TEMPLATE" > "${NAME}-init-cloud-init.yaml"
echo "Cloud-init is created at ${NAME}-init-cloud-init.yaml"

echo "Creating initial server instance: $K3S_SERVER_NAME"

echo "Running $MULTIPASSCMD launch --cpus $SERVER_CPU_MACHINE --disk $SERVER_DISK_MACHINE --memory $SERVER_MEMORY_MACHINE $IMAGE --name $K3S_SERVER_NAME --cloud-init ${NAME}-init-cloud-init.yaml"
$MULTIPASSCMD launch --cpus $SERVER_CPU_MACHINE --disk $SERVER_DISK_MACHINE --memory $SERVER_MEMORY_MACHINE $IMAGE --name $K3S_SERVER_NAME --cloud-init "${NAME}-init-cloud-init.yaml"
if [ $? -ne 0 ]; then
    echo "There was an error launching the instance"
    exit 1
fi

echo "Checking for Node being Ready on $K3S_SERVER_NAME"
$MULTIPASSCMD exec $K3S_SERVER_NAME -- /bin/bash -c 'while [[ $(sudo k3s kubectl get nodes --no-headers 2>/dev/null | grep -c -v "NotReady") -eq 0 ]]; do sleep 2; done'
echo "Node is Ready on $K3S_SERVER_NAME"

# Retrieve info to join agent to cluster
SERVER_IP=$($MULTIPASSCMD info $K3S_SERVER_NAME | grep IPv4 | awk '{ print $2 }')
URL="https://$(echo $SERVER_IP | sed -e 's/[[:space:]]//g'):6443"

# Create additional servers
if [ "${SERVER_COUNT_MACHINE}" -gt 0 ]; then
    read -r -d '' SERVER_CLOUDINIT_TEMPLATE << EOM
#cloud-config

runcmd:
 - '\curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$K3S_VERSION K3S_TOKEN=$SERVER_TOKEN K3S_AGENT_TOKEN=$AGENT_TOKEN INSTALL_K3S_EXEC="server --server $URL" K3S_KUBECONFIG_MODE=644 sh -s - $ADDITIONAL_K3S_SERVER_OPTS'
EOM

    echo "$SERVER_CLOUDINIT_TEMPLATE" > "${NAME}-cloud-init.yaml"

    echo "Creating ${SERVER_COUNT_MACHINE} additional server instances"
    for i in $(eval echo "{1..$SERVER_COUNT_MACHINE}"); do
        echo "Running $MULTIPASSCMD launch --cpus $SERVER_CPU_MACHINE --disk $SERVER_DISK_MACHINE --memory $SERVER_MEMORY_MACHINE $IMAGE --name $K3S_SERVER_NAME-$i --cloud-init ${NAME}-cloud-init.yaml"
        $MULTIPASSCMD launch --cpus $SERVER_CPU_MACHINE --disk $SERVER_DISK_MACHINE --memory $SERVER_MEMORY_MACHINE $IMAGE --name $K3S_SERVER_NAME-$i --cloud-init "${NAME}-cloud-init.yaml"
        if [ $? -ne 0 ]; then
            echo "There was an error launching the instance"
            exit 1
        fi

        echo "Checking for Node being Ready on $K3S_SERVER_NAME"
        $MULTIPASSCMD exec $K3S_SERVER_NAME-$i -- /bin/bash -c 'while [[ $(sudo k3s kubectl get nodes --no-headers 2>/dev/null | grep -c -v "NotReady") -eq 0 ]]; do sleep 2; done'
        echo "Node is Ready on $K3S_SERVER_NAME-${i}"
    done
fi

if [ "${AGENT_COUNT_MACHINE}" -gt 0 ]; then
    # Prepare agent cloud-init
    # Cloud init template
    read -r -d '' AGENT_CLOUDINIT_TEMPLATE << EOM
#cloud-config

runcmd:
 - '\curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=$K3S_VERSION K3S_TOKEN=$AGENT_TOKEN K3S_URL=$URL INSTALL_K3S_EXEC="agent" sh -s -'
EOM

    echo "$AGENT_CLOUDINIT_TEMPLATE" > "${NAME}-agent-cloud-init.yaml"
    echo "Cloud-init is created at ${NAME}-agent-cloud-init.yaml"

    for i in $(eval echo "{1..$AGENT_COUNT_MACHINE}"); do
        echo "Running $MULTIPASSCMD launch --cpus $AGENT_CPU_MACHINE --disk $AGENT_DISK_MACHINE --memory $AGENT_MEMORY_MACHINE $IMAGE --name $K3S_AGENT_NAME-$i --cloud-init ${NAME}-agent-cloud-init.yaml"
        $MULTIPASSCMD launch --cpus $AGENT_CPU_MACHINE --disk $AGENT_DISK_MACHINE --memory $AGENT_MEMORY_MACHINE $IMAGE --name $K3S_AGENT_NAME-$i --cloud-init "${NAME}-agent-cloud-init.yaml"
        if [ $? -ne 0 ]; then
            echo "There was an error launching the instance"
            exit 1
       fi
        echo "Checking for Node $K3S_AGENT_NAME-$i being registered"
        $MULTIPASSCMD exec $K3S_SERVER_NAME -- bash -c "until sudo k3s kubectl get nodes --no-headers | grep -c $K3S_AGENT_NAME-$i 2>/dev/null; do sleep 2; done"
        echo "Checking for Node $K3S_AGENT_NAME-$i being Ready"
        $MULTIPASSCMD exec $K3S_SERVER_NAME -- bash -c "until sudo k3s kubectl get nodes --no-headers | grep $K3S_AGENT_NAME-$i | grep -c -v NotReady 2>/dev/null; do sleep 2; done"
        echo "Node $K3S_AGENT_NAME-$i is Ready on $K3S_SERVER_NAME"
    done
fi

$MULTIPASSCMD copy-files $K3S_SERVER_NAME:/etc/rancher/k3s/k3s.yaml $NAME-kubeconfig-orig.yaml
sed "/^[[:space:]]*server:/ s_:.*_: \"https://$(echo $SERVER_IP | sed -e 's/[[:space:]]//g'):6443\"_" $NAME-kubeconfig-orig.yaml > $NAME-kubeconfig.yaml

if [ -n "$MERGE_KUBECONFIG" ]; then
    cp $KUBECONFIG kubeconfig-$NAME-backup.yaml
    kubectl --kubeconfig $NAME-kubeconfig.yaml config rename-context default $CLUSTER_NAME

    KUBECONFIG=$KUBECONFIG:$NAME-kubeconfig.yaml kubectl config view --flatten > $NAME-kubeconfig-merged.yaml
    cp $NAME-kubeconfig-merged.yaml $KUBECONFIG
fi

echo "k3s setup finished"
$MULTIPASSCMD exec $K3S_SERVER_NAME -- sudo k3s kubectl get nodes
echo "You can now use the following command to connect to your cluster"
echo "$MULTIPASSCMD exec $K3S_SERVER_NAME -- sudo k3s kubectl get nodes"
echo "Or use kubectl directly"
echo "kubectl --kubeconfig ${NAME}-kubeconfig.yaml get nodes"
